---
title: "final_project"
author: "Kee-Young Shin"
date: "December 5, 2018"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(plotly)
```

```{r}

# import hate crime data
hate_offenses_2017 = read_xls("./table-1.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2017"))

hate_offenses_2016 = read_xls("./2016_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2016")) %>% 
  select(1:5)

hate_offenses_2015 = read_xls("./2015_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2015"))
    
hate_offenses_2014 = read_xls("./2014_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2014")) %>% 
  select(1:5)

hate_offenses_2013 = read_xls("./2013_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2013")) %>% 
  select(1:5)

hate_offenses_2012 = read_xls("./2011_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2012"))

hate_offenses_2011 = read_xls("./2011_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2011"))

hate_offenses_2010 = read_xls("./2010_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2010"))

hate_offenses_2009 = read_xls("./2009_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2009"))

hate_offenses_2008 = read_xls("./2008_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2008"))

hate_offenses_2007 = read_xls("./2007_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2007"))

hate_offenses_2006 = read_xls("./2006_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2006"))

hate_offenses_2005 = read_xls("./2005_hatecrime.xls") %>% 
  janitor::clean_names() %>% 
  filter(table_1 == "Total") %>% 
  mutate(table_1 = str_replace(table_1, "Total", "2005"))

# aggregate data for all years
hatecrime_count_df = rbind(hate_offenses_2017, hate_offenses_2016, hate_offenses_2015, 
                           hate_offenses_2014, hate_offenses_2013, hate_offenses_2012,
                           hate_offenses_2011, hate_offenses_2010, hate_offenses_2009,
                           hate_offenses_2008, hate_offenses_2007, hate_offenses_2006,
                           hate_offenses_2005) %>% 
  select(1:3) 
  
colnames(hatecrime_count_df) = c("year", "total_incidents", "total_offenses")
```

```{r}
# plot change in number of hate crimes over time
hatecrime_count_df %>% 
  ggplot(aes(x = year, y = total_incidents)) + geom_line(group = 1, color = "blue")
```

```{r}
# data in 2016
income = read_csv("./data/Income.csv") %>% 
  janitor::clean_names()

unemployment = read_csv("./data/Unemployment.csv") %>% 
  janitor::clean_names()

education = read_csv("./data/Educational_level.csv") %>% 
  janitor::clean_names()

ctizenship = read_csv("./data/Ctizenship.csv") %>% 
  janitor::clean_names()

race = read_csv("./data/Race.csv") %>% 
  janitor::clean_names()

vote = read_csv("./data/Vote.csv") %>% 
  janitor::clean_names()

crime_rate = read_excel("./data/2016.xls",  range = cell_rows(3:53)) %>%
  janitor::clean_names() %>%
  filter(participating_state != "Total") %>%
  select(location = participating_state, population_covered,       total_number_of_incidents_reported) %>%
  mutate(crime_rate = total_number_of_incidents_reported/population_covered*100000) 


ctizenship =
  ctizenship %>% 
  select(location, non_citizen)

race = 
  race %>% 
  select(location, white)

crime_rate =
  crime_rate %>% 
  select(location, crime_rate)

merge_data = 
  merge(income, unemployment, by = "location") %>% 
  merge(., education, by = "location") %>% 
  merge(., ctizenship, by = "location") %>% 
  merge(., race, by = "location") %>% 
  merge(., vote, by = "location") %>%
  merge(., crime_rate, by = "location") %>% 
  filter(location != "United States") %>% 
  rename(state = location, share_unemployed = unemployed, share_non_citizen = non_citizen, share_white = white)
```


#dataset for annual report in state division
```{r}
#list
df = list.files(path = "./annual")
#function
read_data = function(x){read_excel(str_c("./annual/", x),  range = "A3:E53")%>%
    mutate(year = x)}
#map
hate_crime = map(df, read_data)%>%
  bind_rows()%>%
  janitor::clean_names()%>%
  select(-agencies_submitting_incident_reports, -agencies_submitting_incident_reports_2,-agencies_submitting_incident_reports_3)%>%
  mutate(year = str_replace(year, ".xls", ""))%>%
  select(year, everything())
#set na to 0
hate_crime[is.na(hate_crime)]=0

#complete the final dataset
hate_crime = hate_crime%>%
  mutate(total_incident = total_number_of_incidents_reported + total_number_of_incidents_reported_2)%>%
  select(year, state = participating_state, population = population_covered, total_incident)%>%
  filter(state != "Total") %>%
  mutate(annualprop = total_incident/population*100000)%>%
  mutate(year = str_replace(year, ".xls", "")) 
```

```{r}
#do the further cleaning of the merge data
merge_data = merge_data %>%
  mutate(median_annual_household_income = str_replace(median_annual_household_income, ",", "")) %>%
  mutate(median_annual_household_income = gsub("\\$", "",median_annual_household_income )) %>%
mutate(median_annual_household_income = as.numeric(median_annual_household_income)) %>%
  select(state, median_income = median_annual_household_income, everything())
```

##regression part
```{r}
sum(is.na(merge_data))
mle = lm(crime_rate~median_income+share_unemployed+share_population_with_high_school_degree+share_non_citizen+ share_white+ crime_rate, data = merge_data)
multi.fit = step(mle, direction='backward')
summary(multi.fit)
```

```{r}
merge_data%>%
  select(-state, -share_voters_voted_trump)%>%
  select(crime_rate, everything())%>%
  pairs()
```

```{r}
ggplot(merge_data, aes(x = crime_rate)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```




