---
title: "shiny_plot_scrip_marunqi"
author: "Runqi Ma"
date: "2018/12/5"
output: html_document
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(plotly)
```

```{r}
tidy_data = function(data, x){
  data %>% 
  janitor::clean_names() %>% 
  select(table_1, x_1) %>% 
  filter(str_detect(table_1, "Anti")) %>% 
  mutate(type = "i",
         year = x) 
}

hc_2017 = read_xls("./table-1.xls")
hc_2016 = read_xls("./2016_hatecrime.xls")
hc_2015 = read_xls("./2015_hatecrime.xls")
hc_2014 = read_xls("./2014_hatecrime.xls")
hc_2013 = read_xls("./2013_hatecrime.xls")
hc_2012 = read_xls("./2012_hatecrime.xls")
hc_2011 = read_xls("./2011_hatecrime.xls")
hc_2010 = read_xls("./2010_hatecrime.xls")
hc_2009 = read_xls("./2009_hatecrime.xls")
hc_2008 = read_xls("./2008_hatecrime.xls")
hc_2007 = read_xls("./2007_hatecrime.xls")
hc_2006 = read_xls("./2006_hatecrime.xls")
hc_2005 = read_xls("./2005_hatecrime.xls")

change_name = function(data){
  data %>% 
  filter(type != "i") %>% 
  mutate(table_1 = str_replace(table_1, "Anti-American Indian or Alaska Native","Anti-American Indian/Alaskan Native"),
         table_1 = str_replace(table_1, " or African American", ""),
         table_1 = str_replace(table_1, " or Latino", ""),
         table_1 = str_replace(table_1, " \\(Muslim\\)", ""),
         table_1 = str_replace(table_1, "Lesbian", "Female Homosexual"),
         table_1 = str_replace(table_1, "Gay \\(Male\\)", "Male Homosexual"),
         table_1 = str_replace(table_1, "Female Homosexual, Gay\\, Bisexual\\, or Transgender \\(Mixed Group\\)", "Homosexual"))
  
}
```
 
 
```{r}
hc_2017 = tidy_data(hc_2017, 2017)

hc_2017$type[1:9] = "race"
hc_2017$type[10:23] = "religion"
hc_2017$type[24:28] = "sexual orientation"

hc_2017 = 
  change_name(hc_2017) %>%   
  filter(table_1 != "Anti-Asian") %>% 
  mutate(table_1 = str_replace(table_1,"Anti-Native Hawaiian or Other Pacific Islander", "Anti-Asian/Pacific Islander"))

hc_2017$x_1[4] = 147
```

```{r}
hc_2016 = tidy_data(hc_2016, 2016)

hc_2016$type[1:9] = "race"
hc_2016$type[10:23] = "religion"
hc_2016$type[24:28] = "sexual orientation"

hc_2016 = 
  change_name(hc_2016) %>% 
  filter(table_1 != "Anti-Asian") %>%
  mutate(table_1 = str_replace(table_1,"Anti-Native Hawaiian or Other Pacific Islander", "Anti-Asian/Pacific Islander"))

hc_2016$x_1[4] = 122
```

```{r}
hc_2015 = tidy_data(hc_2015, 2015)

hc_2015$type[1:9] = "race"
hc_2015$type[10:23] = "religion"
hc_2015$type[24:28] = "sexual orientation"

hc_2015 = 
  change_name(hc_2015) %>% 
  filter(table_1 != "Anti-Asian") %>%
  mutate(table_1 = str_replace(table_1,"Anti-Native Hawaiian or Other Pacific Islander", "Anti-Asian/Pacific Islander"))

hc_2015$x_1[4] = 115
```


```{r}
hc_2014 = tidy_data(hc_2014, 2014)

hc_2014$type[1:6] = "race"
hc_2014$type[7:13] = "religion"
hc_2014$type[14:18] = "sexual orientation"

hc_2014 = 
  change_name(hc_2014) %>% 
  filter(table_1 != "Anti-Asian") %>%
  mutate(table_1 = str_replace(table_1,"Anti-Native Hawaiian or Other Pacific Islander", "Anti-Asian/Pacific Islander"))

hc_2014$x_1[4] = 143
```


```{r}
hc_2013 = tidy_data(hc_2013, 2013)

hc_2013$type[1:6] = "race"
hc_2013$type[19] = "race"
hc_2013$type[7:13] = "religion"
hc_2013$type[14:18] = "sexual orientation"

hc_2013 = 
  change_name(hc_2013) %>% 
  filter(table_1 != "Anti-Asian") %>%
  mutate(table_1 = str_replace(table_1,"Anti-Native Hawaiian or Other Pacific Islander", "Anti-Asian/Pacific Islander"))

hc_2013$x_1[4] = 138
```

```{r}
hc_2012 = tidy_data(hc_2012, 2012) 

hc_2012$type[1:5] = "race"
hc_2012$type[18] = "race"
hc_2012$type[6:12] = "religion"
hc_2012$type[13:17] = "sexual orientation"

hc_2012 = hc_2012 %>% filter(type != "i")
```

```{r}
hc_2011 = tidy_data(hc_2011, 2011)

hc_2011$type[1:5] = "race"
hc_2011$type[18] = "race"
hc_2011$type[6:12] = "religion"
hc_2011$type[13:17] = "sexual orientation"

hc_2011 = hc_2011 %>% filter(type != "i")
```

```{r}
hc_2010 = tidy_data(hc_2010, 2010) 

hc_2010$type[1:5] = "race"
hc_2010$type[18] = "race"
hc_2010$type[6:12] = "religion"
hc_2010$type[13:17] = "sexual orientation"

hc_2010 = hc_2010 %>% filter(type != "i")
```

```{r}
hc_2009 = tidy_data(hc_2009, 2009) 

hc_2009$type[1:5] = "race"
hc_2009$type[18] = "race"
hc_2009$type[6:12] = "religion"
hc_2009$type[13:17] = "sexual orientation"

hc_2009 = hc_2009 %>% filter(type != "i")
```

```{r}
hc_2008 = tidy_data(hc_2008, 2008) 

hc_2008$type[1:5] = "race"
hc_2008$type[18] = "race"
hc_2008$type[6:12] = "religion"
hc_2008$type[13:17] = "sexual orientation"

hc_2008 = hc_2008 %>% filter(type != "i")
```

```{r}
hc_2007 = tidy_data(hc_2007, 2007) 

hc_2007$type[1:5] = "race"
hc_2007$type[18] = "race"
hc_2007$type[6:12] = "religion"
hc_2007$type[13:17] = "sexual orientation"

hc_2007 = hc_2007 %>% filter(type != "i")
```

```{r}
hc_2006 = tidy_data(hc_2006, 2006) 

hc_2006$type[1:5] = "race"
hc_2006$type[18] = "race"
hc_2006$type[6:12] = "religion"
hc_2006$type[13:17] = "sexual orientation"

hc_2006 = hc_2006 %>% filter(type != "i")
```

```{r}
hc_2005 = tidy_data(hc_2005, 2005) 

hc_2005$type[1:5] = "race"
hc_2005$type[18] = "race"
hc_2005$type[6:12] = "religion"
hc_2005$type[13:17] = "sexual orientation"

hc_2005 = hc_2005 %>% filter(type != "i")
```


```{r}
all_data = rbind(hc_2017, hc_2016, hc_2015, hc_2014, hc_2013, hc_2012, hc_2011, hc_2010, hc_2009, hc_2008, hc_2007, hc_2006, hc_2005) %>% 
  as.tibble() %>% 
  mutate(x_1 = as.numeric(x_1))

```

```{r}
all_data %>% 
    filter(type == "race") %>% 
    plot_ly(x = ~year, y = ~x_1, color = ~table_1, type = "scatter", mode = "lines") %>% 
  layout(showlegend = TRUE, legend = list(orientation = "h", font = list(size = 7)))

all_data %>% 
    filter(type == "religion") %>% 
    plot_ly(x = ~year, y = ~x_1, color = ~table_1, type = "scatter", mode = "lines") %>% 
  layout(showlegend = TRUE, legend = list(orientation = "h", font = list(size = 7)))

all_data %>% 
    filter(type == "sexual orientation") %>% 
    plot_ly(x = ~year, y = ~x_1, color = ~table_1, type = "scatter", mode = "lines") %>% 
  layout(showlegend = TRUE, legend = list(orientation = "h", font = list(size = 7)))
```


```{r, eval=FALSE}
types = all_data %>% distinct(type) %>% pull()

selectInput("type_choice", label = h3("type of hatecrime"),
            choices = types, selected = "race")
            
            
            
            
renderPlotly({
  all_data %>% 
    filter(type == input$type_choice) %>% 
    plot_ly(x = ~year, y = ~x_1, color = ~table_1, type = "scatter", mode = "lines") %>% 
  layout(legend = list(orientation = "h", font = list(size = 8)),
         yaxis = list(title = "Number of incidents"),
         xaxis = list(title = "Year"))
})
```