---
title: "Situation in 2016"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r, include = FALSE}
# data in 2016
income = read_csv("./data/Income.csv") %>% 
  janitor::clean_names()

unemployment = read_csv("./data/Unemployment.csv") %>% 
  janitor::clean_names()

education = read_csv("./data/Educational_level.csv") %>% 
  janitor::clean_names()

ctizenship = read_csv("./data/Ctizenship.csv") %>% 
  janitor::clean_names()

race = read_csv("./data/Race.csv") %>% 
  janitor::clean_names()

vote = read_csv("./data/Vote.csv") %>% 
  janitor::clean_names()

crime_rate = read_excel("./data/2016.xls",  range = cell_rows(3:53)) %>%
  janitor::clean_names() %>%
  filter(participating_state != "Total") %>%
  select(location = participating_state, population_covered,       total_number_of_incidents_reported) %>%
  mutate(crime_rate = total_number_of_incidents_reported/population_covered*100000) 


ctizenship =
  ctizenship %>% 
  select(location, non_citizen)

race = 
  race %>% 
  select(location, white)

crime_rate =
  crime_rate %>% 
  select(location, crime_rate)

merge_data = 
  merge(income, unemployment, by = "location") %>% 
  merge(., education, by = "location") %>% 
  merge(., ctizenship, by = "location") %>% 
  merge(., race, by = "location") %>% 
  merge(., vote, by = "location") %>%
  merge(., crime_rate, by = "location") %>% 
  filter(location != "United States") %>% 
  rename(state = location, share_unemployed = unemployed, share_non_citizen = non_citizen, share_white = white) %>% 
  mutate(median_annual_household_income = str_replace(median_annual_household_income, ",", "")) %>%
  mutate(median_annual_household_income = gsub("\\$", "",median_annual_household_income )) %>%
  mutate(median_annual_household_income = as.numeric(median_annual_household_income)) %>%
  select(state, median_income = median_annual_household_income, everything())
```
