---
title: "Trump Election and Hate Crime"
---

```{r include=FALSE}
library(tidyverse)
library(readxl)
library(plotly)
library(reshape2)
```

```{r include=FALSE}

# data in 2016
income = read_csv("./data/Income.csv") %>% 
  janitor::clean_names()

unemployment = read_csv("./data/Unemployment.csv") %>% 
  janitor::clean_names()

education = read_csv("./data/Educational_level.csv") %>% 
  janitor::clean_names()

ctizenship = read_csv("./data/Ctizenship.csv") %>% 
  janitor::clean_names()

race = read_csv("./data/Race.csv") %>% 
  janitor::clean_names()

vote = read_csv("./data/Vote.csv") %>% 
  janitor::clean_names()

crime_rate = read_excel("./data/2016.xls",  range = cell_rows(3:53)) %>%
  janitor::clean_names() %>%
  filter(participating_state != "Total") %>%
  select(location = participating_state, population_covered,       total_number_of_incidents_reported) %>%
  mutate(crime_rate = total_number_of_incidents_reported/population_covered*100000) 


ctizenship =
  ctizenship %>% 
  select(location, non_citizen)

race = 
  race %>% 
  select(location, white)

crime_rate =
  crime_rate %>% 
  select(location, crime_rate)

merge_data = 
  merge(income, unemployment, by = "location") %>% 
  merge(., education, by = "location") %>% 
  merge(., ctizenship, by = "location") %>% 
  merge(., race, by = "location") %>% 
  merge(., vote, by = "location") %>%
  merge(., crime_rate, by = "location") %>% 
  filter(location != "United States") %>% 
  rename(state = location, share_unemployed = unemployed, share_non_citizen = non_citizen, share_white = white)

merge_data = merge_data %>%
  mutate(median_annual_household_income = str_replace(median_annual_household_income, ",", "")) %>%
  mutate(median_annual_household_income = gsub("\\$", "",median_annual_household_income )) %>%
mutate(median_annual_household_income = as.numeric(median_annual_household_income)) %>%
  select(state, median_income = median_annual_household_income, everything())
```
```{r include=FALSE}

#list
df = list.files(path = "./annual")
#function
read_data = function(x){read_excel(str_c("./annual/", x),  range = "A3:E53")%>%
    mutate(year = x)}
#map
hate_crime = map(df, read_data)%>%
  bind_rows()%>%
  janitor::clean_names()%>%
  select(-agencies_submitting_incident_reports, -agencies_submitting_incident_reports_2,-agencies_submitting_incident_reports_3)%>%
  mutate(year = str_replace(year, ".xls", ""))%>%
  select(year, everything())
#set na to 0
hate_crime[is.na(hate_crime)]=0

#complete the final dataset
hate_crime = hate_crime%>%
  mutate(total_incident = total_number_of_incidents_reported + total_number_of_incidents_reported_2)%>%
  select(year, state = participating_state, population = population_covered, total_incident)%>%
  filter(state != "Total") %>%
  mutate(annualprop = total_incident/population*100000)%>%
  mutate(year = str_replace(year, ".xls", ""))

```

```{r include=FALSE}
hate_crime_10days<-read_csv("./data/hate_crime_10days.csv")
hate_crime_2016<-hate_crime %>% 
  na.omit() %>% 
  filter(year == 2016) %>%
  group_by(state) 

compare_rate<-merge(hate_crime_10days, hate_crime_2016, by= "state")
```




```{r echo=FALSE, fig.align="center"}
compare_rate %>% 
  mutate(hate_crimes_10days_year = hate_crimes_per_100k_splc/10 * 365) %>% 
  select(state, hate_crimes_10days_year, annualprop) %>% 
  melt(, id = "state") %>% 
  mutate(state = reorder(state, value)) %>% 
  ggplot(aes(x = state, y = value, fill = variable, group = variable)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, size = 10, hjust = 1),legend.position = "right")
```

<br>

```{r echo=FALSE}

map_data_2016 = merge_data %>% 
  mutate(state = as.factor(state),
         code = state.abb[state],
         hover = with(merge_data, paste(state,'<br>' ,"share for trump",share_voters_voted_trump))
         ) %>% 
  select(code, crime_rate, hover )

l <- list(color = toRGB("white"), width = 2)
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)


plot_geo(map_data_2016, locationmode = 'USA-states') %>%
  add_trace(
    z = ~ crime_rate, text = ~hover, locations = ~code,
    color = ~ crime_rate, colors = 'Reds'
  ) %>%
  colorbar(title = "Hate crime rate ") %>%
  layout(
    title = 'Hate crime rate in 2016 all over U.S. ',
    geo = g
  )
```

